import numpy as np
import pandas as pd
import shap
from typing import Dict, Any, List, Optional
from app.core.config import settings
from app.services.risk_calculator import model_manager

FEATURE_HUMAN_NAMES = {
    "sleep_hours": "Sleep duration",
    "mood_level": "Mood",
    "stress_level": "Daily stress",
    "hydration_level": "Hydration",
    "screen_time": "Screen time",
    "stress_sleep_ratio": "Stress / sleep interaction",
    "screen_stress": "Screen time / stress interaction",
    "hydration_sleep": "Hydration / sleep interaction",
    "sleep_deficit": "Sleep deficit",
    "hydration_deficit": "Hydration deficit",
    "stress_mood_interaction": "Stress / mood interaction",
    "screen_sleep_ratio": "Screen / sleep interaction",
}


class ShapExplainerService:
    """
    Explainable AI (XAI) service using SHAP for LogisticRegression pipeline.

    SHAP Method Justification:
    The trained classifier is a LogisticRegression estimator operating on StandardScaled features
    z = (x - mu) / sigma generated by MigraineFeatureEngineer.
    LinearExplainer computes exact, analytical additive log-odds feature attributions phi_j = beta_j * z_j
    relative to the standard baseline mean E[z_j] = 0.
    This guarantees exact, deterministic feature contribution ranking without sampling noise.
    """

    def __init__(self):
        self._explainer = None

    def _get_explainer(self, lr_model, feature_count: int = 12):
        if self._explainer is None:
            # Masker reference background mean = 0 for standard scaled features
            zero_background = np.zeros((1, feature_count))
            self._explainer = shap.LinearExplainer(lr_model, zero_background)
        return self._explainer

    def explain(
        self,
        raw_features: Dict[str, Any],
        latest_log: Optional[Dict[str, Any]] = None,
        baseline_stats: Optional[Dict[str, Any]] = None,
        recent_episodes_count_7d: int = 0,
    ) -> Dict[str, Any]:
        if not model_manager.is_loaded or model_manager.model is None:
            raise RuntimeError("Model is not loaded.")

        pipeline = model_manager.model
        fe = pipeline.named_steps["feature_engineering"]
        scaler = pipeline.named_steps["scaler"]
        lr_model = pipeline.named_steps["model"]

        # 1. Transform raw 5 base inputs via trained MigraineFeatureEngineer
        raw_df = pd.DataFrame([
            {
                "sleep_hours": float(raw_features["sleep_hours"]),
                "mood_level": float(raw_features["mood_level"]),
                "stress_level": float(raw_features["stress_level"]),
                "hydration_level": float(raw_features["hydration_level"]),
                "screen_time": float(raw_features["screen_time"]),
            }
        ])

        transformed_df = fe.transform(raw_df)
        feature_names = list(transformed_df.columns)

        # 2. Scale features via StandardScaler
        scaled_X = scaler.transform(transformed_df)

        # 3. Compute SHAP values
        explainer = self._get_explainer(lr_model, len(feature_names))
        shap_explanation = explainer(scaled_X)
        shap_values = shap_explanation.values[0]

        # Handle binary classification 2D output if returned by SHAP version
        if shap_values.ndim > 1:
            shap_values = shap_values[:, 1]

        # 4. Map feature attributions
        features_list = []
        for name, val in zip(feature_names, shap_values):
            shap_val = float(val)
            direction = "increases_risk" if shap_val > 0 else "decreases_risk"
            features_list.append({
                "feature": name,
                "label": FEATURE_HUMAN_NAMES.get(name, name),
                "shap_value": round(shap_val, 4),
                "direction": direction,
                "importance": round(abs(shap_val), 4),
            })

        # Rank all features by absolute importance DESC
        features_sorted = sorted(features_list, key=lambda x: x["importance"], reverse=True)

        # Separate risk-increasing and risk-decreasing factors
        risk_increasing = [f for f in features_sorted if f["direction"] == "increases_risk"]
        risk_decreasing = [f for f in features_sorted if f["direction"] == "decreases_risk"]

        # 5. Build presentation elevated factors from actual API data
        elevated_factors = self._build_elevated_factors(latest_log, baseline_stats, recent_episodes_count_7d)

        return {
            "method": "SHAP",
            "features": features_sorted,
            "risk_increasing_factors": risk_increasing,
            "risk_decreasing_factors": risk_decreasing,
            "elevatedFactors": elevated_factors,
        }

    def _build_elevated_factors(
        self,
        latest_log: Optional[Dict[str, Any]],
        baseline_stats: Optional[Dict[str, Any]],
        recent_episodes_count_7d: int = 0,
    ) -> List[Dict[str, Any]]:
        elevated = []

        if not latest_log:
            return elevated

        # Sleep evaluation
        sleep = float(latest_log.get("sleep_hours", 7.0))
        avg_sleep = float(baseline_stats.get("avg_sleep")) if baseline_stats and baseline_stats.get("avg_sleep") is not None else None

        if avg_sleep is not None:
            diff_sleep = sleep - avg_sleep
            if diff_sleep < 0:
                comp_str = f"{abs(round(diff_sleep, 1))} h below baseline"
            elif diff_sleep > 0:
                comp_str = f"{round(diff_sleep, 1)} h above baseline"
            else:
                comp_str = "Matches baseline"
            desc = f"{sleep} h sleep recorded vs baseline average of {avg_sleep} h."
            sleep_deficit_hours = avg_sleep - sleep
        else:
            comp_str = "No baseline data"
            desc = f"{sleep} h sleep recorded."
            sleep_deficit_hours = 7.0 - sleep

        if sleep_deficit_hours >= settings.PRESENTATION_SLEEP_DEFICIT_ALERT:
            sleep_status = "alert"
        elif sleep_deficit_hours >= settings.PRESENTATION_SLEEP_DEFICIT_WARNING:
            sleep_status = "warning"
        else:
            sleep_status = "stable"

        elevated.append({
            "factor": "Sleep",
            "value": f"{sleep} h",
            "comparison": comp_str,
            "description": desc,
            "statusType": sleep_status,
        })

        # Stress evaluation
        stress = float(latest_log.get("daily_stress", 4.0))
        avg_stress = float(baseline_stats.get("avg_stress")) if baseline_stats and baseline_stats.get("avg_stress") is not None else None

        if avg_stress is not None:
            diff_stress = stress - avg_stress
            if diff_stress > 0:
                comp_str = f"{round(diff_stress, 1)} points above baseline"
            elif diff_stress < 0:
                comp_str = f"{abs(round(diff_stress, 1))} points below baseline"
            else:
                comp_str = "Matches baseline"
            desc = f"Daily stress rating {stress} vs baseline average of {avg_stress}."
            stress_elev = diff_stress
        else:
            comp_str = "No baseline data"
            desc = f"Daily stress rating {stress}."
            stress_elev = stress - 4.0

        if stress >= settings.PRESENTATION_STRESS_HIGH_ALERT or stress_elev >= settings.PRESENTATION_STRESS_ELEVATION_ALERT:
            stress_status = "alert"
        elif stress >= settings.PRESENTATION_STRESS_MOD_WARNING or stress_elev >= settings.PRESENTATION_STRESS_ELEVATION_WARNING:
            stress_status = "warning"
        else:
            stress_status = "stable"

        elevated.append({
            "factor": "Stress",
            "value": f"{stress} / 10",
            "comparison": comp_str,
            "description": desc,
            "statusType": stress_status,
        })

        # Screen time evaluation
        screen = float(latest_log.get("screen_time", 6.0))
        if screen >= settings.PRESENTATION_SCREEN_TIME_ALERT:
            screen_status = "alert"
            screen_desc = f"Heavy screen exposure of {screen} h recorded."
        elif screen >= settings.PRESENTATION_SCREEN_TIME_WARNING:
            screen_status = "warning"
            screen_desc = f"Moderate-to-high screen exposure of {screen} h recorded."
        else:
            screen_status = "stable"
            screen_desc = f"Screen exposure of {screen} h within normal limits."

        elevated.append({
            "factor": "Screen Time",
            "value": f"{screen} h",
            "comparison": "Daily log metric",
            "description": screen_desc,
            "statusType": screen_status,
        })

        # Hydration evaluation
        hydration = float(latest_log.get("hydration", 2.0))
        if hydration <= settings.PRESENTATION_HYDRATION_ALERT:
            hydration_status = "alert"
            hydration_desc = f"Low fluid intake of {hydration} L recorded."
        elif hydration <= settings.PRESENTATION_HYDRATION_WARNING:
            hydration_status = "warning"
            hydration_desc = f"Sub-optimal fluid intake of {hydration} L recorded."
        else:
            hydration_status = "stable"
            hydration_desc = f"Healthy fluid intake of {hydration} L recorded."

        elevated.append({
            "factor": "Hydration",
            "value": f"{hydration} L",
            "comparison": "Daily log metric",
            "description": hydration_desc,
            "statusType": hydration_status,
        })

        return elevated


shap_explainer_service = ShapExplainerService()
